---
- name: pasang nginx
  ansible.builtin.apt:
    name: nginx
    update_cache: yes
    state: present

# - name: salin berkas
#   ansible.builtin.copy:
#     src: files/index.html
#     dest: /var/www/html/index.html
#   notify:
#     - restart nginx

- name: salin template
  ansible.builtin.template:
    src: templates/index.html.j2
    dest: /var/www/html/index.html
  notify:
    - restart nginx
